// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ArreglaOpcioncaracterizacionController from "./arregla_opcioncaracterizacion_controller"
application.register("arregla-opcioncaracterizacion", ArreglaOpcioncaracterizacionController)

import InicializaController from "./inicializa_controller"
application.register("inicializa", InicializaController)

import Sip__CancelarVacioEsEliminarController from "./sip/cancelar_vacio_es_eliminar_controller"
application.register("sip--cancelar-vacio-es-eliminar", Sip__CancelarVacioEsEliminarController)

import Sip__SindocautController from "./sip/sindocaut_controller"
application.register("sip--sindocaut", Sip__SindocautController)

import UsuarioConGrupoController from "./usuario_con_grupo_controller"
application.register("usuario-con-grupo", UsuarioConGrupoController)
